POST http://localhost:8080/polygon
Content-Type: application/json

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -55.7599067687988,
              -11.8655449877911
            ],
            [
              -55.7451868057251,
              -11.8671829190645
            ],
            [
              -55.7480192184448,
              -11.8787321550829
            ],
            [
              -55.7600784301758,
              -11.8760863733273
            ],
            [
              -55.7603788375855,
              -11.8743645015574
            ],
            [
              -55.7599067687988,
              -11.8655449877911
            ]
          ]
        ]
      },
      "properties": {
        "gid": 250,
        "idfarmer": "302a300506032b6570032100385aa9f3942cec5396af0854188937ac7af9d5c7fc2fd9e9c7a21732e6f7f046",
        "companyid": "6",
        "regionid": "00330012001534",
        "countryid": "0033",
        "stateid": "00330012",
        "municipalityid": "00330012001534",
        "technicalid": "123",
        "status": "0",
        "activity": "crops",
        "bsow": 20200701,
        "product": "1",
        "eharvest": "20210301",
        "latcenter": "-11.872",
        "loncenter": "-55.753"
      }
    }
  ]
}
